name: Get branch name
description: Retrieve giithub branch information without `/ref/heads` prefix
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}

outputs:
  base_ref_branch:
    description: 'The target branch of a pull request'
  head_ref_branch:
    description: 'The source branch of a pull request'
  ref_branch:
    description: 'The branch that triggered the workflow run.'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: git-branch
  color: white
