name: Get branch name
description: Retrieve giithub branch information without `/ref/heads` prefix
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  base_ref:
    description: 'The target branch of a pull request'
    default: ${{ github.base_ref }}
    required: false
  head_ref:
    description: 'The source branch of a pull request'
    default: ${{ github.head_ref }}
    required: false
  ref:
    description: 'The branch that triggered the workflow run.'
    default: ${{ github.ref }}
    required: false

outputs:
  base_ref_branch:
    value: ${{ steps.branch.outputs.base_ref_branch }}
    description: 'The target branch of a pull request'
  head_ref_branch:
    value: ${{ steps.branch.outputs.head_ref_branch }}
    description: 'The source branch of a pull request'
  ref_branch:
    value: ${{ steps.branch.outputs.ref_branch }}
    description: 'The branch that triggered the workflow run.'

runs:
  using: "composite"
  steps:
    - id: branch
      run: |
        echo "::set-output name=base_ref_branch::${INPUT_BASE_REF/refs\/heads\//}"
        echo "::set-output name=head_ref_branch::${INPUT_HEAD_REF/refs\/heads\//}"
        echo "::set-output name=ref_branch::${INPUT_REF/refs\/heads\//}"
      shell: bash
branding:
  icon: git-branch
  color: white
