name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test branch-name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        id: branch-name
        uses: ./
      - name: Show output
        run:
          echo "${{ steps.branch-name.outputs.base_ref_branch }}"
          echo "${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "${{ steps.branch-name.outputs.ref_branch }}"
#      - name: Test base ref output
#        if: steps.branch-name.outputs.base_ref_branch
#        run: |
#          exit 1
#      - name: Test head ref output
#        run: |
#          exit 1
#      - name: Test ref output
#        run: |
#          exit 1
